### ISSUE TITLE
Timer events are not sent if an UIScrollView is being scrolled

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#461]

**Comment by sakrra** [comment]
Done

**Comment by rekola** [comment]
How was this fixed?

**Comment by sakrra** [comment]
Now timer fires even if scrollView is scrolled.

iOS Applications run on an NSRunLoop. Each NSRunLoop has different modes of execution for different tasks. For example, the default NSTimer is scheduled to run under the NSDefaultRunMode on the NSRunLoop. What this means however is that certain UIEvents, scrollviewing being one, will interrupt the timer, and place it on a queue to be run as soon as the event stops updating. In this case, in order to get the timer to not be interrupted, timer needs to be scheduled in a different mode, namely NSRunLoopCommonModes.

**Comment by rekola** [comment]
Seems to work.
